<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

/**
 * Notification model — capstone tbl_notifications.
 *
 * Generated by DFD 5.9 (Generate Customer Notification) and by
 * assignment-routing flows. Mobile/web clients poll /api/notifications
 * to receive "push" updates.
 */
class Notification extends Model
{
    /** @use HasFactory<\Database\Factories\NotificationFactory> */
    use HasFactory;

    protected $table = 'tbl_notifications';

    /** @var list<string> */
    protected $fillable = [
        'incident_id',
        'user_id',
        'message',
        'is_read',
        'created_by',
        'updated_by',
    ];

    /** @return array<string, string> */
    protected function casts(): array
    {
        return [
            'is_read' => 'boolean',
        ];
    }

    public function incident(): BelongsTo
    {
        return $this->belongsTo(Incident::class, 'incident_id');
    }

    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class, 'user_id');
    }
}
